inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.4
  Exclude:
    - "spec/**/*"
    - "vendor/**/*"

# Prevents Ruby 3.1 incompatibility error. You can enable this cop when Ruby 2.4 support is dropped.
# See https://github.com/rubocop/rubocop/issues/10258
Layout/BlockAlignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Naming/MethodName:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/GlobalStdStream:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Lint/MissingSuper:
  Enabled: false
