inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.3
  Exclude:
    - "spec/**/*"
    - "vendor/**/*"
Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Naming/MethodName:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
