---

version: "{build}"

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle config --local path vendor/bundle
  - bundle config set --local without 'guard development'
  - bundle install --jobs 3 --retry 3

build: off

cache:
  - vendor/bundle

init:
  - git config --global core.autocrlf true

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake

environment:
  matrix:
    - RUBY_VERSION: 25
    - RUBY_VERSION: 25-x64
    - RUBY_VERSION: 24
    - RUBY_VERSION: 24-x64

matrix:
  fast_finish: true

branches:
  only:
    - master
